# Generated by Django 2.2.11 on 2020-06-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('imc', models.FloatField(verbose_name='IMC')),
                ('hemog', models.FloatField(verbose_name='Hemoglobina')),
                ('hemog_ajustada', models.FloatField(verbose_name='Hemoglobina Ajustada')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
            },
        ),
    ]
