# Generated by Django 3.0.7 on 2020-06-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('imc', models.FloatField(verbose_name='IMC')),
                ('hemog', models.FloatField(verbose_name='Hemoglobina')),
                ('hemog_ajustada', models.FloatField(verbose_name='Hemoglobina Ajustada')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('sex', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1)),
                ('cp', models.IntegerField(choices=[(1.0, 'Angina típica'), (2.0, 'Angina atípica'), (3.0, 'Sin dolor de angina'), (4.0, 'asintomático')], verbose_name='Dolor de pecho')),
                ('trestbps', models.FloatField(verbose_name='Presión de sangre')),
                ('chol', models.FloatField(verbose_name='Colesterol')),
                ('fbs', models.BooleanField(verbose_name='fbs')),
                ('restecg', models.FloatField(choices=[(1.0, 'normal'), (2.0, 'anormal'), (3.0, 'probable hipertrofia ventricular')], verbose_name='Res. electrocardiográficos')),
                ('thalach', models.FloatField(verbose_name='Nivel maximo de frecuencia cardiaca')),
                ('exang', models.BooleanField(verbose_name='Angila inducida por ejercicio')),
                ('oldpeak', models.IntegerField(verbose_name='Depresión ST inducida')),
                ('slope', models.FloatField(choices=[(1.0, 'bajo'), (2.0, 'medio'), (3.0, 'alto')], verbose_name='Pico más alto')),
                ('ca', models.FloatField(verbose_name='Núm vasos principales')),
                ('thal', models.FloatField(choices=[(3.0, 'normal'), (6.0, 'defecto solucionable'), (7.0, 'defecto reversible')], verbose_name='thal')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
            },
        ),
    ]
