# Generated by Django 3.0.7 on 2020-06-26 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0002_auto_20200625_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='chol',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='exang',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fbs',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='oldpeak',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='restecg',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='slope',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='thal',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='thalach',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='trestbps',
        ),
    ]
