# Generated by Django 3.0.7 on 2020-06-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0005_auto_20200625_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sex',
        ),
    ]
