# Generated by Django 3.0.7 on 2020-06-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('som', '0007_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('sex', models.IntegerField(choices=[(0, 'MASCULINO'), (1, 'FEMENINO')], verbose_name='Sexo')),
                ('cp', models.IntegerField(choices=[(1, 'Angina típica'), (2, 'Angina atípica'), (3, 'Sin dolor de angina'), (4, 'asintomático')], verbose_name='Dolor de pecho')),
                ('trestbps', models.IntegerField(verbose_name='Presión de sangre')),
                ('chol', models.FloatField(verbose_name='Colesterol')),
                ('fbs', models.IntegerField(verbose_name='fbs')),
                ('restecg', models.IntegerField(choices=[(1, 'normal'), (2, 'anormal'), (3, 'probable hipertrofia ventricular')], verbose_name='Res. electrocardiográficos')),
                ('thalach', models.IntegerField(verbose_name='Nivel maximo de frecuencia cardiaca')),
                ('exang', models.IntegerField(verbose_name='Angila inducida por ejercicio')),
                ('oldpeak', models.IntegerField(verbose_name='Depresión ST inducida')),
                ('slope', models.IntegerField(choices=[(1, 'bajo'), (2, 'medio'), (3, 'alto')], verbose_name='Pico más alto')),
                ('ca', models.IntegerField(verbose_name='Núm vasos principales')),
                ('thal', models.IntegerField(choices=[(3, 'normal'), (6, 'defecto solucionable'), (7, 'defecto reversible')], verbose_name='thal')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
            },
        ),
    ]
