# Generated by Django 3.0.7 on 2020-06-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0008_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ca',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='Núm vasos principales'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='exang',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'si')], verbose_name='Angila inducida por ejercicio'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fbs',
            field=models.IntegerField(choices=[(0, 'verdader'), (1, 'falso')], verbose_name='Nivel de azúcar en ayuna'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='restecg',
            field=models.IntegerField(choices=[(0, 'normal'), (1, 'anormal'), (2, 'probable hipertrofia ventricular')], verbose_name='Res. electrocardiográficos'),
        ),
    ]
