# Generated by Django 3.0.7 on 2020-06-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0009_auto_20200625_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fbs',
            field=models.IntegerField(choices=[(0, 'VERDADERO'), (1, 'FALSO')], verbose_name='Nivel de azúcar en ayuna'),
        ),
    ]
