# Generated by Django 2.2.11 on 2020-06-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0010_auto_20200625_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='result',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fbs',
            field=models.IntegerField(choices=[(0, 'VERDADERO'), (1, 'FALSO')], verbose_name='Nivel de azúcar en ayuno'),
        ),
    ]
