# Generated by Django 2.2.11 on 2020-06-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0011_auto_20200626_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chol',
            field=models.PositiveIntegerField(verbose_name='Colesterol'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='oldpeak',
            field=models.PositiveIntegerField(verbose_name='Depresión ST inducida'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='thalach',
            field=models.PositiveIntegerField(verbose_name='Nivel maximo de frecuencia cardiaca'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='trestbps',
            field=models.PositiveIntegerField(verbose_name='Presión de sangre'),
        ),
    ]
