# Generated by Django 2.2.11 on 2020-06-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('som', '0012_auto_20200627_0046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
