# Generated by Django 2.2.11 on 2020-06-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('som', '0013_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('sex', models.IntegerField(choices=[(0, 'MASCULINO'), (1, 'FEMENINO')], verbose_name='Sexo')),
                ('cp', models.IntegerField(choices=[(1, 'Angina típica'), (2, 'Angina atípica'), (3, 'Sin dolor de angina'), (4, 'asintomático')], verbose_name='Dolor de pecho')),
                ('trestbps', models.PositiveIntegerField(verbose_name='Presión de sangre')),
                ('chol', models.PositiveIntegerField(verbose_name='Colesterol')),
                ('fbs', models.IntegerField(choices=[(0, 'VERDADERO'), (1, 'FALSO')], verbose_name='Nivel de azúcar en ayuno')),
                ('restecg', models.IntegerField(choices=[(0, 'normal'), (1, 'anormal'), (2, 'probable hipertrofia ventricular')], verbose_name='Res. electrocardiográficos')),
                ('thalach', models.PositiveIntegerField(verbose_name='Nivel maximo de frecuencia cardiaca')),
                ('exang', models.IntegerField(choices=[(0, 'no'), (1, 'si')], verbose_name='Angila inducida por ejercicio')),
                ('oldpeak', models.PositiveIntegerField(verbose_name='Depresión ST inducida')),
                ('slope', models.IntegerField(choices=[(1, 'bajo'), (2, 'medio'), (3, 'alto')], verbose_name='Pico más alto')),
                ('ca', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='Núm vasos principales')),
                ('thal', models.IntegerField(choices=[(3, 'normal'), (6, 'defecto solucionable'), (7, 'defecto reversible')], verbose_name='thal')),
                ('result', models.IntegerField(blank=True, null=True, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
            },
        ),
    ]
